Warn if PETSc is already initialised inside petsctools.init. (#38)
* Warn if PETSc is already initialised inside petsctools.init.

This functionality was rejected from petsc4py and so should live here.
It is unfortunately complicated due to the petsc4py init process.

Also tidies up some docstrings and moves some exceptions to
exceptions.py which is now the established convention.

diff --git a/.github/workflows/core.yml b/.github/workflows/core.yml
--- a/.github/workflows/core.yml
+++ b/.github/workflows/core.yml
@@ -113,18 +113,24 @@ jobs:
           . venv-petsctools/bin/activate
           pip install --verbose $PETSC_DIR/src/binding/petsc4py
 
-      # Make sure that running 'import petsctools' does not initialise PETSc
-      # (e.g. by running 'from petsc4py import PETSc'). Otherwise 'petsctools.init'
-      # does nothing. We check this by passing a PETSc option on the command line
-      # and making sure that it is processed.
-      - name: Test lazy PETSc initialisation
+      - name: Test PETSc initialisation
         if: success() || steps.install-petsc4py.conclusion == 'success'
         run: |
           . venv-petsctools/bin/activate
+
+          : # Make sure that running 'import petsctools' does not initialise PETSc
+          : # (e.g. by running 'from petsc4py import PETSc'). Otherwise 'petsctools.init'
+          : # does nothing. We check this by passing a PETSc option on the command line
+          : # and making sure that it is processed.
           if [ -z "$( python -c 'import petsctools; petsctools.init()' -log_view | grep 'PETSc Performance Summary' )" ]; then
+            echo "ERROR: '-log_view' flag not passed to PETSc"
             exit 1
-          else
-            exit 0
+          fi
+
+          : # Test that running 'petsctools.init' after PETSc is initialised raises a warning
+          if [ -z "$( 2>&1 python -c 'import petsc4py, petsctools; petsc4py.init(); petsctools.init()' | grep 'PETSc has already been initialised' )" ]; then
+            echo "ERROR: petsctools.init should have raised a warning"
+            exit 1
           fi
 
       - name: Run tests with petsc4py
